[build]
publish = "."

[[headers]]
for = "/*"
  [headers.values]
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
for = "/templates/*.pdf"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"
